wandb_mode: offline
use_custom_requeue: False

precision: 16-mixed
batch_size: 1
gpus: 8
cpus: 4


launcher:
    cpus_per_task: 4
    gpus_per_node: 8
    nodes: 1
    tasks_per_node: 1
    mem_gb: ${eval:'32 * min(${cluster.gpus}, 8)'}
    timeout_min: 1440
    name: ${name}
    slurm_constraint: 
    slurm_account: 
    slurm_additional_parameters:
      hint: nomultithread
    slurm_srun_args:
      - "--cpu-bind=none"
      - "--mem-bind=none"
